[workspace]
members = ["crates/sefy-core", "crates/sefy-cli"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/lacodda/sefy"
homepage = "https://github.com/lacodda/sefy"
authors = ["Kirill Lakhtachev <lahtachev@gmail.com>"]

[workspace.dependencies]
sefy-core = { path = "crates/sefy-core", version = "0.0.1" }

argon2 = "0.5"
chacha20poly1305 = { version = "0.11", features = ["alloc"] }
getrandom = "0.3"
rusqlite = { version = "0.40", features = ["bundled", "serialize"] }
thiserror = "2"
zeroize = { version = "1", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
